tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "glib"
brew "llvm"
brew "ccls"
brew "clang-format"
brew "direnv"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "jq"
brew "krb5"
brew "lua"
brew "mas"
brew "zlib"
brew "mysql"
brew "mysql-client"
brew "neovim"
brew "nodebrew"
brew "openjdk"
brew "openssl@3"
brew "postgresql@14", restart_service: true
brew "procs"
brew "python@3.9"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shared-mime-info"
brew "terminal-notifier"
brew "tig"
brew "tmux"
brew "watchman"
brew "zsh-git-prompt"
cask "app-cleaner"
cask "bettertouchtool"
cask "clipy"
cask "docker"
cask "figma"
cask "firefox"
cask "gather"
cask "google-chrome"
cask "google-japanese-ime"
cask "jasper"
cask "karabiner-elements"
cask "ngrok"
cask "postman"
cask "raycast"
cask "skitch"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "zoom"
mas "Keynote", id: 409183694
mas "Microsoft PowerPoint", id: 462062816
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RunCat", id: 1429033973
